name: delivery_ctpaga
description: Ctlleva.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.25+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  cached_network_image: ^2.2.0+1
  cupertino_icons: ^0.1.3
  dio: ^3.0.9
  ext_storage: ^1.0.3
  flutter_local_notifications: ^1.4.4+2
  flutter_localizations:
    sdk: flutter
  flutter_masked_text: ^0.8.0
  flutter_ringtone_player: ^2.0.0
  fluttertoast: ^7.1.8
  file_picker: ^2.1.7
  firebase_messaging: ^7.0.3
  geocoding: ^1.0.5
  geolocator: ^6.1.13
  geocoder: ^0.2.1
  google_maps_flutter: ^1.0.6
  http: ^0.12.2
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+12
  install_plugin: ^2.0.1
  searchable_dropdown: ^1.1.3
  shared_preferences: ^0.5.7+3
  package_info: ^0.4.3
  path_provider: ^1.6.22
  permission_handler: ^5.0.0
  provider: ^4.3.2+2
  pusher_websocket_flutter: ^0.2.0
  sqflite: ^1.1.6
  url_launcher: ^5.5.2
  webview_flutter: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter:

  uses-material-design: true

  assets:
    - assets/logo/
    - assets/icons/
  
  fonts:
    - family: MontserratMedium   
      fonts:
        - asset: assets/Fonts/Montserrat-Medium.ttf

    - family: MontserratBold     
      fonts:
        - asset: assets/Fonts/Montserrat-Bold.ttf

    - family: MontserratBlack     
      fonts:
        - asset: assets/Fonts/Montserrat-Black.ttf

    - family: MontserratSemiBold     
      fonts:
        - asset: assets/Fonts/Montserrat-SemiBold.ttf

    - family: MontserratExtraBold    
      fonts:
        - asset: assets/Fonts/Montserrat-ExtraBold.ttf

    - family: MontserratItalic     
      fonts:
        - asset: assets/Fonts/Montserrat-Italic.ttf

    - family: MontserratLight     
      fonts:
        - asset: assets/Fonts/Montserrat-Light.ttf

    - family: MontserratExtraLight     
      fonts:
        - asset: assets/Fonts/Montserrat-ExtraLight.ttf

flutter_icons:
  image_path: 'assets/logo/ICONO-CTLLEVA.png'
  android: true
  ios: true
