name: delivery_ctpaga
description: Ctlleva.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.31+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.4
  dio: ^4.0.6
  flutter_local_notifications: ^9.5.3+1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.10
  flutter_masked_text: ^0.8.0
  flutter_ringtone_player: ^3.1.1
  fluttertoast: ^8.0.9
  file_picker: ^4.4.0
  firebase_messaging: ^11.2.7
  geocoding: ^2.0.4
  geolocator: ^8.0.5
  google_maps_flutter: ^2.0.9
  http: ^0.13.3
  image_cropper: ^1.3.1
  image_picker: ^0.8.4+1
  search_choices : ^2.0.19
  shared_preferences: ^2.0.7
  package_info: ^2.0.2
  path_provider: ^2.0.4
  permission_handler: ^8.1.6
  provider: ^6.0.2
  sqflite: ^2.0.2
  url_launcher: ^6.0.10
  webview_flutter: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
    - assets/icons/
  
  fonts:
    - family: MontserratMedium   
      fonts:
        - asset: assets/Fonts/Montserrat-Medium.ttf

    - family: MontserratBold     
      fonts:
        - asset: assets/Fonts/Montserrat-Bold.ttf

    - family: MontserratBlack     
      fonts:
        - asset: assets/Fonts/Montserrat-Black.ttf

    - family: MontserratSemiBold     
      fonts:
        - asset: assets/Fonts/Montserrat-SemiBold.ttf

    - family: MontserratExtraBold    
      fonts:
        - asset: assets/Fonts/Montserrat-ExtraBold.ttf

    - family: MontserratItalic     
      fonts:
        - asset: assets/Fonts/Montserrat-Italic.ttf

    - family: MontserratLight     
      fonts:
        - asset: assets/Fonts/Montserrat-Light.ttf

    - family: MontserratExtraLight     
      fonts:
        - asset: assets/Fonts/Montserrat-ExtraLight.ttf

flutter_icons:
  image_path: 'assets/logo/ICONO-CTLLEVA.png'
  android: true
  ios: true
